apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-java-sj
  namespace: bermtec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-sj
  template:
    metadata:
      labels:
        app: dotnet-sj
    spec:
      containers:
      - name: dotnet-sj-test
        image: shubham4994/donet-sj:1.0.0
        ports:
        - containerPort: 5000