apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dotnet-java-sj-hpa
  namespace: bermtec
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnet-java-sj
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Target average CPU utilization percentage
