apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dotnet-sj-rolebinding
  namespace: bermtec
subjects:
- kind: ServiceAccount
  name: dotnet-sj-sa
  namespace: bermtec
roleRef:
  kind: Role
  name: dotnet-sj-role
  apiGroup: rbac.authorization.k8s.io
